app1/urls.py
from django.urls import path
from app1.views import *

app_name='anushka'

urlpatterns = [
    path('arundhati/',arundhati,name='arundhati'),
]

app2/urls.py
from django.urls import path
from app2.views import *

app_name='sonu'

urlpatterns = [
    path('pashupati/',pashupati,name='pashupati'),
]

project7/urls.py
from django.contrib import admin
from django.urls import path,include
import app1,app2
urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def arundhati(request):
    return render(request,'arundhati.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def pashupati(request):
    return render(request,'pashupati.html')

templates/arundhati.html
<!DOCTYPE html>
<html>
<head>
    <title>Document</title>
</head>
<body>
    <center>
        <h1>action</h1>
        <h1>Nuvv nannem cheyyalevu raa</h1>
<h2><a href="{% url 'sonu:pashupati' %}">dialogue of pashupati</a></h2>
    </center>
</body>
</html>

templates/pashupati.html
<!DOCTYPE html>
<html lang="eng">
<head>
    <title>Document</title>
</head>
<body>
    <center>
        <h1>action</h1>
        <h1>Vadhala Bommali Vadhalaa......</h1>
<h2><a href="{% url 'anushka:arundhati' %}">dialogue of anushka</a></h2>
    </center>
</body>
</html> 